accounts: 
  account_1:
    # this is all_regions except cn-north-1 and us-gov-west-1
    all_regions: True
  account_2:
    regions:
      # any regions listed will have all_listed_regions_policies run
      us-east-2:
        # region_policies are only run in this region alone
        # 'region_policies':
        #  - 'ec2-enforce-tagging.yml'
# all_listed_regions_policies get run only in regions listed under accounts.
# So if you did all_regions, each of the global run policies would run in all regions.
# If you only listed us-east-1 under a regions key for an account, only us-east-1 would be run.
all_listed_regions_policies:
  - ebs-garbage-collect-unattached-volumes.yml
